version: '2'

services:

  moodle_db:
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - 'moodledb_apache:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'moodle'
      POSTGRES_USER: 'moodle'
      POSTGRES_PASSWORD: 'password'

  moodle:
    image: ellakcy/moodle:postgresql_apache_latest
    #volumes:
    #  - './data/moodle/data:/var/moodledata'
    #  - 'www_apache:/var/www/html'
    ports:
      - '8082:80'
    links:
      - moodle_db
    environment:
      MOODLE_URL: 'http://localhost:8082'
      MOODLE_ADMIN: 'admin'
      MOODLE_ADMIN_PASSWORD: 'password'
      MOODLE_ADMIN_EMAIL: 'test@test.com'
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_USER: 'moodle'
      MOODLE_DB_PASSWORD: 'password'
      MOODLE_DB_NAME: 'moodle'
      MOODLE_REVERSE_LB: 'false'
      MOODLE_SSL: 'false'
      MOODLE_EMAIL_TYPE_QMAIL: 'false'
      MOODLE_EMAIL_HOST: 'test.com'

volumes:
  moodledb_apache:
  www_apache: